Repository openshift/console-crontab-plugin, pull requests merged in 2025-07, with the labels that each got.

#36 OCPBUGS-59541: fix integration test setup for CI
  integration-tests/views/common.ts
Labels: px-approved, docs-approved, lgtm, qe-approved, approved, jira/valid-bug, jira/valid-reference

#38 OCPBUGS-59554: update openshift SDK to 4.19.0
  Dockerfile
  package.json
  yarn.lock
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#40 [release-4.19] OCPBUGS-59585: Proper fix now that openshift/console#15302 merged
  integration-tests/e2e/crud.cy.ts
  integration-tests/views/common.ts
Labels: lgtm, tide/merge-method-squash, backport-risk-assessed, approved, jira/valid-bug, jira/valid-reference

#39 [release-4.19] OCPBUGS-59584: update openshift SDK to 4.19.0
  Dockerfile
  package.json
  yarn.lock
Labels: lgtm, backport-risk-assessed, approved, jira/valid-bug, jira/valid-reference

#42 [release-4.18] OCPBUGS-59891: Proper fix now that https://github.com/openshift/conso…
  integration-tests/views/common.ts
Labels: lgtm, backport-risk-assessed, approved, jira/valid-bug, jira/valid-reference
